import { Emoji } from "../types";

export const emojis: Emoji[] = [
  { code: "U+1F600", emoji: "😀", description: "grinning face" },
  { code: "U+1F603", emoji: "😃", description: "grinning face with big eyes" },
  {
    code: "U+1F604",
    emoji: "😄",
    description: "grinning face with smiling eyes",
  },
  {
    code: "U+1F601",
    emoji: "😁",
    description: "beaming face with smiling eyes",
  },
  { code: "U+1F606", emoji: "😆", description: "grinning squinting face" },
  { code: "U+1F605", emoji: "😅", description: "grinning face with sweat" },
  {
    code: "U+1F923",
    emoji: "🤣",
    description: "rolling on the floor laughing",
  },
  { code: "U+1F602", emoji: "😂", description: "face with tears of joy" },
  { code: "U+1F642", emoji: "🙂", description: "slightly smiling face" },
  { code: "U+1F643", emoji: "🙃", description: "upside-down face" },
  { code: "U+1F609", emoji: "😉", description: "winking face" },
  {
    code: "U+1F60A",
    emoji: "😊",
    description: "smiling face with smiling eyes",
  },
  { code: "U+1F607", emoji: "😇", description: "smiling face with halo" },
  { code: "U+1F970", emoji: "🥰", description: "smiling face with hearts" },
  { code: "U+1F60D", emoji: "😍", description: "smiling face with heart-eyes" },
  { code: "U+1F929", emoji: "🤩", description: "star-struck" },
  { code: "U+1F618", emoji: "😘", description: "face blowing a kiss" },
  { code: "U+1F617", emoji: "😗", description: "kissing face" },
  {
    code: "U+1F61A",
    emoji: "😚",
    description: "kissing face with closed eyes",
  },
  {
    code: "U+1F619",
    emoji: "😙",
    description: "kissing face with smiling eyes",
  },
  { code: "U+1F60B", emoji: "😋", description: "face savoring food" },
  { code: "U+1F61B", emoji: "😛", description: "face with tongue" },
  { code: "U+1F61C", emoji: "😜", description: "winking face with tongue" },
  { code: "U+1F92A", emoji: "🤪", description: "zany face" },
  { code: "U+1F61D", emoji: "😝", description: "squinting face with tongue" },
  { code: "U+1F911", emoji: "🤑", description: "money-mouth face" },
  { code: "U+1F917", emoji: "🤗", description: "hugging face" },
  { code: "U+1F92D", emoji: "🤭", description: "face with hand over mouth" },
  { code: "U+1F92B", emoji: "🤫", description: "shushing face" },
  { code: "U+1F914", emoji: "🤔", description: "thinking face" },
  { code: "U+1F910", emoji: "🤐", description: "zipper-mouth face" },
  { code: "U+1F928", emoji: "🤨", description: "face with raised eyebrow" },
  { code: "U+1F610", emoji: "😐", description: "neutral face" },
  { code: "U+1F611", emoji: "😑", description: "expressionless face" },
  { code: "U+1F636", emoji: "😶", description: "face without mouth" },
  { code: "U+1F60F", emoji: "😏", description: "smirking face" },
  { code: "U+1F612", emoji: "😒", description: "unamused face" },
  { code: "U+1F644", emoji: "🙄", description: "face with rolling eyes" },
  { code: "U+1F62C", emoji: "😬", description: "grimacing face" },
  { code: "U+1F925", emoji: "🤥", description: "lying face" },
  { code: "U+1F60C", emoji: "😌", description: "relieved face" },
  { code: "U+1F614", emoji: "😔", description: "pensive face" },
  { code: "U+1F62A", emoji: "😪", description: "sleepy face" },
  { code: "U+1F924", emoji: "🤤", description: "drooling face" },
  { code: "U+1F634", emoji: "😴", description: "sleeping face" },
  { code: "U+1F637", emoji: "😷", description: "face with medical mask" },
  { code: "U+1F912", emoji: "🤒", description: "face with thermometer" },
  { code: "U+1F915", emoji: "🤕", description: "face with head-bandage" },
  { code: "U+1F922", emoji: "🤢", description: "nauseated face" },
  { code: "U+1F92E", emoji: "🤮", description: "face vomiting" },
  { code: "U+1F927", emoji: "🤧", description: "sneezing face" },
  { code: "U+1F975", emoji: "🥵", description: "hot face" },
  { code: "U+1F976", emoji: "🥶", description: "cold face" },
  { code: "U+1F974", emoji: "🥴", description: "woozy face" },
  { code: "U+1F635", emoji: "😵", description: "dizzy face" },
  { code: "U+1F92F", emoji: "🤯", description: "exploding head" },
  { code: "U+1F920", emoji: "🤠", description: "cowboy hat face" },
  { code: "U+1F973", emoji: "🥳", description: "partying face" },
  { code: "U+1F60E", emoji: "😎", description: "smiling face with sunglasses" },
  { code: "U+1F913", emoji: "🤓", description: "nerd face" },
  { code: "U+1F9D0", emoji: "🧐", description: "face with monocle" },
  { code: "U+1F615", emoji: "😕", description: "confused face" },
  { code: "U+1F61F", emoji: "😟", description: "worried face" },
  { code: "U+1F641", emoji: "🙁", description: "slightly frowning face" },
  { code: "U+1F62E", emoji: "😮", description: "face with open mouth" },
  { code: "U+1F62F", emoji: "😯", description: "hushed face" },
  { code: "U+1F632", emoji: "😲", description: "astonished face" },
  { code: "U+1F633", emoji: "😳", description: "flushed face" },
  { code: "U+1F97A", emoji: "🥺", description: "pleading face" },
  {
    code: "U+1F626",
    emoji: "😦",
    description: "frowning face with open mouth",
  },
  { code: "U+1F627", emoji: "😧", description: "anguished face" },
  { code: "U+1F628", emoji: "😨", description: "fearful face" },
  { code: "U+1F630", emoji: "😰", description: "anxious face with sweat" },
  { code: "U+1F625", emoji: "😥", description: "sad but relieved face" },
  { code: "U+1F622", emoji: "😢", description: "crying face" },
  { code: "U+1F62D", emoji: "😭", description: "loudly crying face" },
  { code: "U+1F631", emoji: "😱", description: "face screaming in fear" },
  { code: "U+1F616", emoji: "😖", description: "confounded face" },
  { code: "U+1F623", emoji: "😣", description: "persevering face" },
  { code: "U+1F61E", emoji: "😞", description: "disappointed face" },
  { code: "U+1F613", emoji: "😓", description: "downcast face with sweat" },
  { code: "U+1F629", emoji: "😩", description: "weary face" },
  { code: "U+1F62B", emoji: "😫", description: "tired face" },
  { code: "U+1F624", emoji: "😤", description: "face with steam from nose" },
  { code: "U+1F621", emoji: "😡", description: "pouting face" },
  { code: "U+1F620", emoji: "😠", description: "angry face" },
  { code: "U+1F92C", emoji: "🤬", description: "face with symbols on mouth" },
  { code: "U+1F608", emoji: "😈", description: "smiling face with horns" },
  { code: "U+1F47F", emoji: "👿", description: "angry face with horns" },
  { code: "U+1F480", emoji: "💀", description: "skull" },
  { code: "U+1F4A9", emoji: "💩", description: "pile of poo" },
  { code: "U+1F921", emoji: "🤡", description: "clown face" },
  { code: "U+1F479", emoji: "👹", description: "ogre" },
  { code: "U+1F47A", emoji: "👺", description: "goblin" },
  { code: "U+1F47B", emoji: "👻", description: "ghost" },
  { code: "U+1F47D", emoji: "👽", description: "alien" },
  { code: "U+1F47E", emoji: "👾", description: "alien monster" },
  { code: "U+1F916", emoji: "🤖", description: "robot" },

  { code: "U+1F63A", emoji: "😺", description: "grinning cat" },
  {
    code: "U+1F638",
    emoji: "😸",
    description: "grinning cat with smiling eyes",
  },
  { code: "U+1F639", emoji: "😹", description: "cat with tears of joy" },
  { code: "U+1F63B", emoji: "😻", description: "smiling cat with heart-eyes" },
  { code: "U+1F63C", emoji: "😼", description: "cat with wry smile" },
  { code: "U+1F63D", emoji: "😽", description: "kissing cat" },
  { code: "U+1F640", emoji: "🙀", description: "weary cat" },
  { code: "U+1F63F", emoji: "😿", description: "crying cat" },
  { code: "U+1F63E", emoji: "😾", description: "pouting cat" },
  { code: "U+1F648", emoji: "🙈", description: "see-no-evil monkey" },
  { code: "U+1F649", emoji: "🙉", description: "hear-no-evil monkey" },
  { code: "U+1F64A", emoji: "🙊", description: "speak-no-evil monkey" },
  { code: "U+1F48B", emoji: "💋", description: "kiss mark" },
  { code: "U+1F48C", emoji: "💌", description: "love letter" },
  { code: "U+1F498", emoji: "💘", description: "heart with arrow" },
  { code: "U+1F49D", emoji: "💝", description: "heart with ribbon" },
  { code: "U+1F496", emoji: "💖", description: "sparkling heart" },
  { code: "U+1F497", emoji: "💗", description: "growing heart" },
  { code: "U+1F493", emoji: "💓", description: "beating heart" },
  { code: "U+1F49E", emoji: "💞", description: "revolving hearts" },
  { code: "U+1F495", emoji: "💕", description: "two hearts" },
  { code: "U+1F49F", emoji: "💟", description: "heart decoration" },
  { code: "U+1F494", emoji: "💔", description: "broken heart" },
  { code: "U+1F9E1", emoji: "🧡", description: "orange heart" },
  { code: "U+1F49B", emoji: "💛", description: "yellow heart" },
  { code: "U+1F49A", emoji: "💚", description: "green heart" },
  { code: "U+1F499", emoji: "💙", description: "blue heart" },
  { code: "U+1F49C", emoji: "💜", description: "purple heart" },
  { code: "U+1F5A4", emoji: "🖤", description: "black heart" },
  { code: "U+1F4AF", emoji: "💯", description: "hundred points" },
  { code: "U+1F4A2", emoji: "💢", description: "anger symbol" },
  { code: "U+1F4A5", emoji: "💥", description: "collision" },
  { code: "U+1F4AB", emoji: "💫", description: "dizzy" },
  { code: "U+1F4A6", emoji: "💦", description: "sweat droplets" },
  { code: "U+1F4A8", emoji: "💨", description: "dashing away" },
  { code: "U+1F573", emoji: "🕳", description: "hole" },
  { code: "U+1F4A3", emoji: "💣", description: "bomb" },
  { code: "U+1F4AC", emoji: "💬", description: "speech balloon" },
  {
    code: "U+1F441 U+FE0F U+200D U+1F5E8 U+FE0F",
    emoji: "👁️‍🗨️",
    description: "eye in speech bubble",
  },
  { code: "U+1F5E8", emoji: "🗨", description: "left speech bubble" },
  { code: "U+1F5EF", emoji: "🗯", description: "right anger bubble" },
  { code: "U+1F4AD", emoji: "💭", description: "thought balloon" },
  { code: "U+1F4A4", emoji: "💤", description: "zzz" },
  { code: "U+1F44B", emoji: "👋", description: "waving hand" },
  { code: "U+1F91A", emoji: "🤚", description: "raised back of hand" },
  { code: "U+1F590", emoji: "🖐", description: "hand with fingers splayed" },
  { code: "U+270B", emoji: "✋", description: "raised hand" },
  { code: "U+1F596", emoji: "🖖", description: "vulcan salute" },
  { code: "U+1F44C", emoji: "👌", description: "OK hand" },
  { code: "U+1F91E", emoji: "🤞", description: "crossed fingers" },
  { code: "U+1F91F", emoji: "🤟", description: "love-you gesture" },
  { code: "U+1F918", emoji: "🤘", description: "sign of the horns" },
  { code: "U+1F919", emoji: "🤙", description: "call me hand" },
  { code: "U+1F448", emoji: "👈", description: "backhand index pointing left" },
  {
    code: "U+1F449",
    emoji: "👉",
    description: "backhand index pointing right",
  },
  { code: "U+1F446", emoji: "👆", description: "backhand index pointing up" },
  { code: "U+1F595", emoji: "🖕", description: "middle finger" },
  { code: "U+1F447", emoji: "👇", description: "backhand index pointing down" },
  { code: "U+1F44D", emoji: "👍", description: "thumbs up" },
  { code: "U+1F44E", emoji: "👎", description: "thumbs down" },
  { code: "U+270A", emoji: "✊", description: "raised fist" },
  { code: "U+1F44A", emoji: "👊", description: "oncoming fist" },
  { code: "U+1F91B", emoji: "🤛", description: "left-facing fist" },
  { code: "U+1F91C", emoji: "🤜", description: "right-facing fist" },
  { code: "U+1F44F", emoji: "👏", description: "clapping hands" },
  { code: "U+1F64C", emoji: "🙌", description: "raising hands" },
  { code: "U+1F450", emoji: "👐", description: "open hands" },
  { code: "U+1F932", emoji: "🤲", description: "palms up together" },
  { code: "U+1F91D", emoji: "🤝", description: "handshake" },
  { code: "U+1F64F", emoji: "🙏", description: "folded hands" },
  { code: "U+1F485", emoji: "💅", description: "nail polish" },
  { code: "U+1F933", emoji: "🤳", description: "selfie" },
  { code: "U+1F4AA", emoji: "💪", description: "flexed biceps" },
  { code: "U+1F9B5", emoji: "🦵", description: "⊛ leg" },
  { code: "U+1F9B6", emoji: "🦶", description: "⊛ foot" },
  { code: "U+1F442", emoji: "👂", description: "ear" },
  { code: "U+1F443", emoji: "👃", description: "nose" },
  { code: "U+1F9E0", emoji: "🧠", description: "brain" },
  { code: "U+1F9B7", emoji: "🦷", description: "⊛ tooth" },
  { code: "U+1F9B4", emoji: "🦴", description: "⊛ bone" },
  { code: "U+1F440", emoji: "👀", description: "eyes" },
  { code: "U+1F441", emoji: "👁", description: "eye" },
  { code: "U+1F445", emoji: "👅", description: "tongue" },
  { code: "U+1F444", emoji: "👄", description: "mouth" },
  { code: "U+1F476", emoji: "👶", description: "baby" },
  { code: "U+1F9D2", emoji: "🧒", description: "child" },
  { code: "U+1F466", emoji: "👦", description: "boy" },
  { code: "U+1F467", emoji: "👧", description: "girl" },
  { code: "U+1F9D1", emoji: "🧑", description: "person" },
  { code: "U+1F471", emoji: "👱", description: "person: blond hair" },
  { code: "U+1F468", emoji: "👨", description: "man" },
  { code: "U+1F9D4", emoji: "🧔", description: "man: beard" },
  {
    code: "U+1F471 U+200D U+2642 U+FE0F",
    emoji: "👱‍♂️",
    description: "man: blond hair",
  },
  {
    code: "U+1F468 U+200D U+1F9B0",
    emoji: "👨‍🦰",
    description: "⊛ man: red hair",
  },
  {
    code: "U+1F468 U+200D U+1F9B1",
    emoji: "👨‍🦱",
    description: "⊛ man: curly hair",
  },
  { code: "U+1F468 U+200D U+1F9B2", emoji: "👨‍🦲", description: "⊛ man: bald" },
  { code: "U+1F469", emoji: "👩", description: "woman" },
  {
    code: "U+1F471 U+200D U+2640 U+FE0F",
    emoji: "👱‍♀️",
    description: "woman: blond hair",
  },
  {
    code: "U+1F469 U+200D U+1F9B0",
    emoji: "👩‍🦰",
    description: "woman: red hair",
  },
  {
    code: "U+1F469 U+200D U+1F9B1",
    emoji: "👩‍🦱",
    description: "woman: curly hair",
  },
  {
    code: "U+1F469 U+200D U+1F9B3",
    emoji: "👩‍🦳",
    description: "woman: white hair",
  },
  { code: "U+1F469 U+200D U+1F9B2", emoji: "👩‍🦲", description: "⊛ woman: bald" },
  { code: "U+1F9D3", emoji: "🧓", description: "older person" },
  { code: "U+1F474", emoji: "👴", description: "old man" },
  { code: "U+1F475", emoji: "👵", description: "old woman" },
  { code: "U+1F64D", emoji: "🙍", description: "person frowning" },
  {
    code: "U+1F64D U+200D U+2642 U+FE0F",
    emoji: "🙍‍♂️",
    description: "man frowning",
  },
  {
    code: "U+1F64D U+200D U+2640 U+FE0F",
    emoji: "🙍‍♀️",
    description: "woman frowning",
  },
  { code: "U+1F64E", emoji: "🙎", description: "person pouting" },
  {
    code: "U+1F64E U+200D U+2642 U+FE0F",
    emoji: "🙎‍♂️",
    description: "man pouting",
  },
  {
    code: "U+1F64E U+200D U+2640 U+FE0F",
    emoji: "🙎‍♀️",
    description: "woman pouting",
  },
  { code: "U+1F645", emoji: "🙅", description: "person gesturing NO" },
  {
    code: "U+1F645 U+200D U+2642 U+FE0F",
    emoji: "🙅‍♂️",
    description: "man gesturing NO",
  },
  {
    code: "U+1F645 U+200D U+2640 U+FE0F",
    emoji: "🙅‍♀️",
    description: "woman gesturing NO",
  },
  { code: "U+1F646", emoji: "🙆", description: "person gesturing OK" },
  {
    code: "U+1F646 U+200D U+2642 U+FE0F",
    emoji: "🙆‍♂️",
    description: "man gesturing OK",
  },
  {
    code: "U+1F646 U+200D U+2640 U+FE0F",
    emoji: "🙆‍♀️",
    description: "woman gesturing OK",
  },
  { code: "U+1F481", emoji: "💁", description: "person tipping hand" },
  {
    code: "U+1F481 U+200D U+2642 U+FE0F",
    emoji: "💁‍♂️",
    description: "man tipping hand",
  },
  {
    code: "U+1F481 U+200D U+2640 U+FE0F",
    emoji: "💁‍♀️",
    description: "woman tipping hand",
  },
  { code: "U+1F64B", emoji: "🙋", description: "person raising hand" },
  {
    code: "U+1F64B U+200D U+2642 U+FE0F",
    emoji: "🙋‍♂️",
    description: "man raising hand",
  },
  {
    code: "U+1F64B U+200D U+2640 U+FE0F",
    emoji: "🙋‍♀️",
    description: "woman raising hand",
  },
  { code: "U+1F647", emoji: "🙇", description: "person bowing" },
  {
    code: "U+1F647 U+200D U+2642 U+FE0F",
    emoji: "🙇‍♂️",
    description: "man bowing",
  },
  {
    code: "U+1F647 U+200D U+2640 U+FE0F",
    emoji: "🙇‍♀️",
    description: "woman bowing",
  },
  { code: "U+1F926", emoji: "🤦", description: "person facepalming" },
  {
    code: "U+1F926 U+200D U+2642 U+FE0F",
    emoji: "🤦‍♂️",
    description: "man facepalming",
  },
  {
    code: "U+1F926 U+200D U+2640 U+FE0F",
    emoji: "🤦‍♀️",
    description: "woman facepalming",
  },
  { code: "U+1F937", emoji: "🤷", description: "person shrugging" },
  {
    code: "U+1F937 U+200D U+2642 U+FE0F",
    emoji: "🤷‍♂️",
    description: "man shrugging",
  },
  {
    code: "U+1F937 U+200D U+2640 U+FE0F",
    emoji: "🤷‍♀️",
    description: "woman shrugging",
  },
  {
    code: "U+1F468 U+200D U+2695 U+FE0F",
    emoji: "👨‍⚕️",
    description: "man health worker",
  },
  {
    code: "U+1F469 U+200D U+2695 U+FE0F",
    emoji: "👩‍⚕️",
    description: "woman health worker",
  },
  { code: "U+1F468 U+200D U+1F393", emoji: "👨‍🎓", description: "man student" },
  { code: "U+1F469 U+200D U+1F393", emoji: "👩‍🎓", description: "woman student" },
  { code: "U+1F468 U+200D U+1F3EB", emoji: "👨‍🏫", description: "man teacher" },
  { code: "U+1F469 U+200D U+1F3EB", emoji: "👩‍🏫", description: "woman teacher" },
  {
    code: "U+1F468 U+200D U+2696 U+FE0F",
    emoji: "👨‍⚖️",
    description: "man judge",
  },
  {
    code: "U+1F469 U+200D U+2696 U+FE0F",
    emoji: "👩‍⚖️",
    description: "woman judge",
  },
  { code: "U+1F468 U+200D U+1F33E", emoji: "👨‍🌾", description: "man farmer" },
  { code: "U+1F469 U+200D U+1F33E", emoji: "👩‍🌾", description: "woman farmer" },
  { code: "U+1F468 U+200D U+1F373", emoji: "👨‍🍳", description: "man cook" },
  { code: "U+1F469 U+200D U+1F373", emoji: "👩‍🍳", description: "woman cook" },
  { code: "U+1F468 U+200D U+1F527", emoji: "👨‍🔧", description: "man mechanic" },
  {
    code: "U+1F469 U+200D U+1F527",
    emoji: "👩‍🔧",
    description: "woman mechanic",
  },
  {
    code: "U+1F468 U+200D U+1F3ED",
    emoji: "👨‍🏭",
    description: "man factory worker",
  },
  {
    code: "U+1F469 U+200D U+1F3ED",
    emoji: "👩‍🏭",
    description: "woman factory worker",
  },
  {
    code: "U+1F468 U+200D U+1F4BC",
    emoji: "👨‍💼",
    description: "man office worker",
  },
  {
    code: "U+1F469 U+200D U+1F4BC",
    emoji: "👩‍💼",
    description: "woman office worker",
  },
  { code: "U+1F468 U+200D U+1F52C", emoji: "👨‍🔬", description: "man scientist" },
  {
    code: "U+1F469 U+200D U+1F52C",
    emoji: "👩‍🔬",
    description: "woman scientist",
  },
  {
    code: "U+1F468 U+200D U+1F4BB",
    emoji: "👨‍💻",
    description: "man technologist",
  },
  {
    code: "U+1F469 U+200D U+1F4BB",
    emoji: "👩‍💻",
    description: "woman technologist",
  },
  { code: "U+1F468 U+200D U+1F3A4", emoji: "👨‍🎤", description: "man singer" },
  { code: "U+1F469 U+200D U+1F3A4", emoji: "👩‍🎤", description: "woman singer" },
  { code: "U+1F468 U+200D U+1F3A8", emoji: "👨‍🎨", description: "man artist" },
  { code: "U+1F469 U+200D U+1F3A8", emoji: "👩‍🎨", description: "woman artist" },
  {
    code: "U+1F468 U+200D U+2708 U+FE0F",
    emoji: "👨‍✈️",
    description: "man pilot",
  },
  {
    code: "U+1F469 U+200D U+2708 U+FE0F",
    emoji: "👩‍✈️",
    description: "woman pilot",
  },
  { code: "U+1F468 U+200D U+1F680", emoji: "👨‍🚀", description: "man astronaut" },
  {
    code: "U+1F469 U+200D U+1F680",
    emoji: "👩‍🚀",
    description: "woman astronaut",
  },
  {
    code: "U+1F468 U+200D U+1F692",
    emoji: "👨‍🚒",
    description: "man firefighter",
  },
  {
    code: "U+1F469 U+200D U+1F692",
    emoji: "👩‍🚒",
    description: "woman firefighter",
  },
  { code: "U+1F46E", emoji: "👮", description: "police officer" },
  {
    code: "U+1F46E U+200D U+2642 U+FE0F",
    emoji: "👮‍♂️",
    description: "man police officer",
  },
  {
    code: "U+1F46E U+200D U+2640 U+FE0F",
    emoji: "👮‍♀️",
    description: "woman police officer",
  },
  { code: "U+1F575", emoji: "🕵", description: "detective" },
  {
    code: "U+1F575 U+FE0F U+200D U+2642 U+FE0F",
    emoji: "🕵️‍♂️",
    description: "man detective",
  },
  {
    code: "U+1F575 U+FE0F U+200D U+2640 U+FE0F",
    emoji: "🕵️‍♀️",
    description: "woman detective",
  },
  { code: "U+1F482", emoji: "💂", description: "guard" },
  {
    code: "U+1F482 U+200D U+2642 U+FE0F",
    emoji: "💂‍♂️",
    description: "man guard",
  },
  {
    code: "U+1F482 U+200D U+2640 U+FE0F",
    emoji: "💂‍♀️",
    description: "woman guard",
  },
  { code: "U+1F477", emoji: "👷", description: "construction worker" },
  {
    code: "U+1F477 U+200D U+2642 U+FE0F",
    emoji: "👷‍♂️",
    description: "man construction worker",
  },
  {
    code: "U+1F477 U+200D U+2640 U+FE0F",
    emoji: "👷‍♀️",
    description: "woman construction worker",
  },
  { code: "U+1F934", emoji: "🤴", description: "prince" },
  { code: "U+1F478", emoji: "👸", description: "princess" },
  { code: "U+1F473", emoji: "👳", description: "person wearing turban" },
  {
    code: "U+1F473 U+200D U+2642 U+FE0F",
    emoji: "👳‍♂️",
    description: "man wearing turban",
  },
  {
    code: "U+1F473 U+200D U+2640 U+FE0F",
    emoji: "👳‍♀️",
    description: "woman wearing turban",
  },
  { code: "U+1F472", emoji: "👲", description: "man with Chinese cap" },
  { code: "U+1F9D5", emoji: "🧕", description: "woman with headscarf" },
  { code: "U+1F935", emoji: "🤵", description: "man in tuxedo" },
  { code: "U+1F470", emoji: "👰", description: "bride with veil" },
  { code: "U+1F930", emoji: "🤰", description: "pregnant woman" },
  { code: "U+1F931", emoji: "🤱", description: "breast-feeding" },
  { code: "U+1F47C", emoji: "👼", description: "baby angel" },
  { code: "U+1F385", emoji: "🎅", description: "Santa Claus" },
  { code: "U+1F936", emoji: "🤶", description: "Mrs. Claus" },
  { code: "U+1F9B8", emoji: "🦸", description: "⊛ superhero" },
  {
    code: "U+1F9B8 U+200D U+2642 U+FE0F",
    emoji: "🦸‍♂️",
    description: "⊛ man superhero",
  },
  {
    code: "U+1F9B8 U+200D U+2640 U+FE0F",
    emoji: "🦸‍♀️",
    description: "⊛ woman superhero",
  },
];
